deployment_id_label_order:
  - namespace
  - network_name
  - provider
  - environment
  - region
  - stack
  - deployment_id

remote_state_path_label_order:
  - namespace
  - stack
  - provider
  - network_name
  - environment
  - region
#  - deployment_id

dns_order:
  - region
  - provider
  - network_name
  - namespace

id_label_order:
  - namespace
  - stack
  - network_name
  - environment

short_id_label_order:
  - stack
  - environment

name_label_order:
  - namespace
  - stack
  - network_name
  - environment

network_settings:
  polkadot:
    name: polkadot
    shortname: polkadot
    api_health: 5000
    node_exporter: 9610
    json_rpc: 9933
    ws_rpc: 9944
  kusama:
    name: kusama
    shortname: ksmcc3
    api_health: 5001
    node_exporter: 9611
    json_rpc: 9934
    ws_rpc: 9945